# Generated by Django 2.1.7 on 2020-05-03 08:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('pages', '0001_initial'), ('pages', '0002_faq_studentteam'), ('pages', '0003_branch_mentor'), ('pages', '0004_contactdetails'), ('pages', '0005_auto_20190321_1320'), ('pages', '0006_auto_20191126_1957'), ('pages', '0007_auto_20191126_2001'), ('pages', '0008_blogs'), ('pages', '0009_auto_20191127_0300'), ('pages', '0010_events'), ('pages', '0011_studentteam_position'), ('pages', '0012_auto_20200227_1750'), ('pages', '0013_mentordocs'), ('pages', '0014_auto_20200228_0853'), ('pages', '0015_auto_20200228_0913'), ('pages', '0016_faq__for'), ('pages', '0017_auto_20200308_0912'), ('pages', '0018_raisedquery'), ('pages', '0019_teamposition'), ('pages',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      '0020_auto_20200408_1343'), ('pages', '0021_auto_20200408_1446'), ('pages', '0022_auto_20200408_1826'), ('pages', '0023_auto_20200408_1852'), ('pages', '0019_auto_20200406_1754'), ('pages', '0020_blogs_is_featured'), ('pages', '0024_merge_20200410_1249'), ('pages', '0025_mentorachievement'), ('pages', '0026_mentorintern'), ('pages', '0027_auto_20200414_2337'), ('pages', '0028_auto_20200418_0743'), ('pages', '0029_auto_20200418_0904'), ('pages', '0030_auto_20200418_0910'), ('pages', '0031_auto_20200418_0912'), ('pages', '0032_mentor_career'), ('pages', '0033_delete_mentordocs'), ('pages', '0034_auto_20200429_0218'), ('pages', '0035_auto_20200502_2017')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('smp_description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HomeVision',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=300)),
                ('answer', models.CharField(default='', max_length=1000)),
                ('_for', models.CharField(blank=True, choices=[
                 ('mentor', 'MENTOR'), ('mentee', 'MENTEE')], default='mentor', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(max_length=200, upload_to='members/')),
                ('facebook', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('linkedin', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('branch', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pages.branch')),
                ('year', models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), (
                    '3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[
                 ('Manager', 'Manager'), ('Coordinator', 'Coordinator')], max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('mobile', models.IntegerField(null=True)),
                ('vertical', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Operations', 'Operations'), (
                    'WebD', 'WebD'), ('Events', 'Events'), ('Content', 'Content'), ('Design', 'Design')], max_length=100, null=True)),
                ('enrollno', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(max_length=200, upload_to='members/')),
                ('facebook', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('linkedin', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('branch', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(default='', max_length=100)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True,
                                                max_length=200, null=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True,
                                                max_length=200, null=True, upload_to='events/')),
                ('venue', models.CharField(default='', max_length=100)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='RaisedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CampusGroups',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(
                    blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='blogs_category', to='pages.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
