# Generated by Django 2.1.7 on 2020-05-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200503_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusgroups',
            name='thumbnail',
            field=models.ImageField(
                max_length=200, null=True, upload_to='groups/'),
        ),
        migrations.AddField(
            model_name='campusgroups',
            name='website',
            field=models.URLField(blank=True, db_index=True, max_length=1000),
        ),
    ]
