# Generated by Django 2.1.7 on 2020-05-24 17:08

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200513_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile',
            field=models.CharField(default='', max_length=100, validators=[
                                   common.validators.validate_mobile]),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='email',
            field=models.CharField(default='', max_length=100, validators=[
                                   common.validators.validate_iitr_email]),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='enrollno',
            field=models.IntegerField(null=True, validators=[
                                      common.validators.validate_enroll]),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='mobile',
            field=models.IntegerField(null=True, validators=[
                                      common.validators.validate_mobile]),
        ),
    ]
