# Generated by Django 2.1.7 on 2020-10-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200508_0400'),
        ('pages', '0004_auto_20200524_2238'),
    ]

    operations = [
    ]
