# Generated by Django 2.1.7 on 2020-10-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_merge_20201012_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentteam',
            name='vertical',
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='team_position', to='pages.TeamPosition'),
            preserve_default=False,
        ),
    ]
