# Generated by Django 2.1.7 on 2020-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteam',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
