# Generated by Django 2.1.7 on 2020-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_studentteam_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteam',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentteam',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
    ]
