# Generated by Django 2.1.7 on 2020-03-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_faq__for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='_for',
            field=models.CharField(blank=True, choices=[('mentor', 'MENTOR'), ('mentee', 'MENTEE')], default='mentor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.CharField(blank=True, choices=[('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='pages.branch'),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='year',
            field=models.CharField(blank=True, choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=100, null=True),
        ),
    ]
