# Generated by Django 2.1.7 on 2020-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_auto_20200308_0912"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaisedQuery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("query", models.TextField()),
            ],
        ),
    ]
