# Generated by Django 2.1.7 on 2020-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_raisedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPosition',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
