# Generated by Django 2.1.7 on 2020-04-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200406_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
