# Generated by Django 2.1.7 on 2020-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200408_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteam',
            name='vertical',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Operations', 'Operations'), ('WebD', 'WebD'), ('Eventts', 'Events'), ('Content', 'Content'), ('Design', 'Design')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='position',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Coordinator', 'Coordinator')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TeamPosition',
        ),
    ]
