# Generated by Django 2.1.7 on 2020-04-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_blogs_is_featured'),
        ('pages', '0023_auto_20200408_1852'),
    ]

    operations = [
    ]
