# Generated by Django 2.1.7 on 2020-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_mentorintern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
