# Generated by Django 2.1.7 on 2020-04-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200414_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='linkden',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='linkden',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='studentteam',
            old_name='linkden',
            new_name='linkedin',
        ),
    ]
