# Generated by Django 2.1.7 on 2020-04-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200418_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='enrollno',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='facebook',
            field=models.URLField(blank=True, db_index=True,
                                  max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True, db_index=True,
                                  max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
