# Generated by Django 2.1.7 on 2020-04-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200418_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='facebook',
            field=models.URLField(
                db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(
                db_index=True, max_length=1000, null=True, unique=True),
        ),
    ]
