# Generated by Django 2.1.7 on 2020-04-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20200418_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='facebook',
            field=models.URLField(blank=True, db_index=True,
                                  default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedin',
            field=models.URLField(blank=True, db_index=True,
                                  default='', max_length=1000),
            preserve_default=False,
        ),
    ]
