# Generated by Django 2.1.7 on 2020-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20200418_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='career',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
