# Generated by Django 2.1.7 on 2020-04-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_mentor_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorDocs',
        ),
    ]
