# Generated by Django 2.1.7 on 2020-04-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_delete_mentordocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_placement', to='pages.Mentor')),
            ],
        ),
        migrations.AlterField(
            model_name='studentteam',
            name='vertical',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Operations', 'Operations'), ('WebD', 'WebD'), (
                'Events', 'Events'), ('Content', 'Content'), ('Design', 'Design')], max_length=100, null=True),
        ),
    ]
