# Generated by Django 2.1.7 on 2020-05-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20200429_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='mentorachievement',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorintern',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentorplacement',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='MentorAchievement',
        ),
        migrations.DeleteModel(
            name='MentorIntern',
        ),
        migrations.DeleteModel(
            name='MentorPlacement',
        ),
    ]
