# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
exclude: .*.svg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.1.1
  #   hooks:
  #       - id: seed-isort-config
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.21 # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
  #   hooks:
  #       - id: isort
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier
  # - repo: https://github.com/ambv/black
  #   rev: stable
  #   hooks:
  #     - id: black
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.1
    hooks:
      - id: autopep8
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: "" # pick a git hash / tag to point to
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        # additional_dependencies:
        #     - babel-eslint
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: ""
  #   hooks:
  #       - id: markdownlint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.0.0
    hooks:
      #   - id: check-mailmap
      #   - id: forbid-binary
      #   - id: forbid-space-in-indent
      #   - id: git-check # Configure in .gitattributes
      #   - id: git-dirty # Configure in .gitignore
      - id: markdownlint # Configure in .mdlrc
      #   - id: require-ascii
