# Generated by Django 2.1.7 on 2021-02-13 13:34

import common.rename
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(
                    default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=200, null=True,
                                            upload_to=common.rename.FileUploader('mentors/images', 'student'))),
                ('resume', models.FileField(
                    null=True, upload_to=common.rename.FileUploader('mentors/resume', 'student'))),
                ('mobile', models.CharField(blank=True, max_length=10, null=True,
                                            unique=True, validators=[common.validators.validate_mobile])),
                ('facebook', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('linkedin', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('year', models.CharField(blank=True, choices=[
                 ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=15, null=True)),
                ('career', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True,
                                                  related_name='campus_groups_mentor', to='pages.CampusGroup')),
                ('interest', models.ManyToManyField(blank=True,
                                                    related_name='interest', to='mentors.Interest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='mentor_student', to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_achievement', to='mentors.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('year', models.CharField(blank=True, choices=[
                 ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=15, null=True)),
                ('motivation', models.TextField(
                    blank=True, max_length=1000, null=True)),
                ('qualities', models.TextField(
                    blank=True, max_length=1000, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True,
                                            unique=True, validators=[common.validators.validate_mobile])),
                ('resume', models.FileField(null=True, upload_to=common.rename.FileUploader(
                    'mentors/applied/resume', 'student'))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='mentor_application_student', to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MentorIntern',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.TextField(blank=True, max_length=500, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_intern', to='mentors.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_placement', to='mentors.Mentor')),
            ],
        ),
    ]
