# Generated by Django 2.1.7 on 2020-05-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0035_auto_20200502_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(
                    default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('photo', models.ImageField(
                    max_length=200, upload_to='mentors/images')),
                ('resume', models.FileField(null=True, upload_to='mentors/resume')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('mobile', models.IntegerField(null=True, unique=True)),
                ('enrollno', models.IntegerField(null=True, unique=True)),
                ('facebook', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('linkedin', models.URLField(
                    blank=True, db_index=True, max_length=1000)),
                ('year', models.CharField(blank=True, choices=[
                 ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=100, null=True)),
                ('career', models.CharField(blank=True, max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentors', to='pages.branch')),
                ('groups', models.ManyToManyField(blank=True,
                                                  related_name='campus_groups_mentor', to='pages.CampusGroups')),
                ('interest', models.ManyToManyField(blank=True,
                                                    related_name='interest', to='mentors.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_achievement', to='mentors.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorIntern',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.TextField(blank=True, max_length=500, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_intern', to='mentors.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='mentor_placement', to='mentors.Mentor')),
            ],
        ),
    ]
