# Generated by Django 2.1.7 on 2020-05-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='enrollno',
            field=models.IntegerField(unique=True),
        ),
    ]
