# Generated by Django 2.1.7 on 2020-05-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_auto_20200503_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='year',
            field=models.CharField(blank=True, choices=[(
                '3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=15, null=True),
        ),
    ]
