# Generated by Django 2.1.7 on 2020-05-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_auto_20200503_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='branch',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='pages.Branch'),
        ),
    ]
