# Generated by Django 2.1.7 on 2020-05-12 15:58

from django.db import migrations, models
import django.db.models.deletion
import mentors.models
import common.rename


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200503_2048'),
        ('mentors', '0004_auto_20200503_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('enrollno', models.IntegerField(unique=True)),
                ('year', models.CharField(blank=True, choices=[
                 ('3rd', '3rd Year'), ('4th', '4th Year'), ('5th', '5th Year')], max_length=15, null=True)),
                ('motivation', models.TextField(
                    blank=True, max_length=1000, null=True)),
                ('qualities', models.TextField(
                    blank=True, max_length=1000, null=True)),
                ('mobile', models.IntegerField(null=True, unique=True)),
                ('resume', models.FileField(
                    null=True, upload_to=common.rename.UploadToPathAndRename('mentors/applied/resume', 'student'))),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='applied_mentor', to='pages.Branch')),
            ],
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(
                max_length=200, upload_to=common.rename.UploadToPathAndRename('mentors/images', 'student')),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='resume',
            field=models.FileField(
                null=True, upload_to=common.rename.UploadToPathAndRename('mentors/resume', 'student')),
        ),
    ]
