# Generated by Django 2.1.7 on 2020-05-24 18:12

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20200524_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True, validators=[
                                    common.validators.validate_iitr_email]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='enrollno',
            field=models.IntegerField(unique=True, validators=[
                                      common.validators.validate_enroll]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='mobile',
            field=models.IntegerField(null=True, unique=True, validators=[
                                      common.validators.validate_mobile]),
        ),
    ]
