# Generated by Django 2.1.7 on 2020-10-16 13:02

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_auto_20201016_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[
                                   common.validators.validate_mobile]),
        ),
    ]
