# Generated by Django 2.1.7 on 2020-10-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentors', '0010_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='mentor_application', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
