# Generated by Django 2.1.7 on 2020-10-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0011_mentorapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='mentor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='mentor_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
