# Generated by Django 2.1.7 on 2020-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0012_auto_20201024_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
