# Generated by Django 2.1.7 on 2020-10-29 15:26

import common.rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0013_mentorapplication_isaccepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to=common.rename.FileUploader(
                'mentors/images', 'student')),
        ),
    ]
