# Generated by Django 2.1.7 on 2020-11-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0014_auto_20201029_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorapplication',
            old_name='isAccepted',
            new_name='is_accepted',
        ),
    ]
